# Generated by Django 3.2.18 on 2023-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_diarys/'),
        ),
        migrations.AddField(
            model_name='tcat',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='TcatImage',
        ),
    ]
